parameters:
    ezsettings.admin_group.content_edit.templates.edit: '@@EzPlatformAdminUi/content/content_edit/content_edit.html.twig'
    ezsettings.admin_group.content_edit.templates.create: '@@EzPlatformAdminUi/content/content_edit/content_create.html.twig'
    ezsettings.admin_group.content_edit.templates.create_draft: '@@EzPlatformAdminUi/content/content_edit/content_create_draft.html.twig'
    ezsettings.admin_group.user_edit.templates.update: '@@EzPlatformAdminUi/content/content_edit/user_edit.html.twig'
    ezsettings.admin_group.user_edit.templates.create: '@@EzPlatformAdminUi/content/content_edit/user_create.html.twig'

    ezsettings.global.system_info_view:
        pjax_tab:
            composer:
                template: '@@EzPlatformAdminUi/admin/systeminfo/composer.html.twig'
                match:
                    SystemInfo\Identifier: 'composer'
            database:
                template: '@@EzPlatformAdminUi/admin/systeminfo/database.html.twig'
                match:
                    SystemInfo\Identifier: 'database'
            hardware:
                template: '@@EzPlatformAdminUi/admin/systeminfo/hardware.html.twig'
                match:
                    SystemInfo\Identifier: 'hardware'
            php:
                template: '@@EzPlatformAdminUi/admin/systeminfo/php.html.twig'
                match:
                    SystemInfo\Identifier: 'php'
            symfony_kernel:
                template: '@@EzPlatformAdminUi/admin/systeminfo/symfony_kernel.html.twig'
                match:
                    SystemInfo\Identifier: 'symfony_kernel'

    ezplatform.content_view.tabs.default_template: '@@EzPlatformAdminUi/parts/tab/default.html.twig'

    ezplatform.multifile_upload.location.mappings: []

    ezplatform.multifile_upload.location.default_mappings:
        # Image
        - mime_types:
            - image/jpeg
            - image/jpg
            - image/pjpeg
            - image/pjpg
            - image/png
            - image/bmp
            - image/gif
            - image/tiff
            - image/x-icon
            - image/webp
          content_type_identifier: image
          content_field_identifier: image
          name_field_identifier: name
        # File
        - mime_types:
            - image/svg+xml
            - application/msword
            - application/vnd.openxmlformats-officedocument.wordprocessingml.document
            - application/vnd.ms-excel
            - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
            - application/vnd.ms-powerpoint
            - application/vnd.openxmlformats-officedocument.presentationml.presentation
            - application/pdf
          content_type_identifier: file
          content_field_identifier: file
          name_field_identifier: name

    ezplatform.multifile_upload.fallback_content_type:
        content_type_identifier: file
        content_field_identifier: file
        name_field_identifier: name

    ez_systems.multifile_upload.max_file_size: 5242880

